### ISSUE TITLE
chore!: remove SPANNER support from Janssen distribution

### ISSUE THREAD

**Issue by moabu** [JanssenProject/jans#10042]
### Description

- [x] Drop from AS @yuriyz 
- [x] Drop from config-api @pujavs 
- [x] Drop from setup/tui @devrimyatar https://github.com/JanssenProject/jans/issues/10040
- [x] Drop from image @iromli @moabu https://github.com/JanssenProject/jans/issues/10046
- [x] Drop from charts @iromli @moabu https://github.com/JanssenProject/jans/issues/10061
- [x] #10056

**Comment by pujavs** [comment]
Verified there is no SPANNER specific code in `config-api`

**Comment by yuriyz** [comment]
I've removed spanner from jenkins FullRebuild. All subtasks are closed. We can consider this ticket as done.
