### ISSUE TITLE
feat(jans-auth-server): add new scope attributes - creatorType/creatorId/createDate

### ISSUE THREAD

**Issue by yuriyz** [JanssenProject/jans#1874]
### Description

We have to add creator attributes to scope. In this way we can keep who, when and how created scope.

```

{
  "creatorType": "person",
  "creatorId": "12345-abcdef"
  "createDate": "12321934890128310"
}
```

### Tasks

- [ ] Implement on AS
- [ ] Updat scope documentation
- [ ] Communicate with UI devs

**Comment by yuriyz** [comment]
Already added as part of https://github.com/JanssenProject/jans/issues/1934 . Closing this ticket.
