### ISSUE TITLE
feat(jans-auth-server): add Token Status List support to AS

### ISSUE THREAD

**Issue by yuriyz** [JanssenProject/jans#8562]
### Description

Add Token Status List support to AS

https://datatracker.ietf.org/doc/html/draft-ietf-oauth-status-list-02

### Tasks
- [ ] Provide unique index (possible via separate `jansTokenIndex` table)
- [ ] Provide index for each token and persist it. JWT must return it as "idx".
- [ ] Introduce jansNode table to track node id with lockKey, see https://github.com/JanssenProject/jans/wiki/Jans-Lock-revoked-token-list-integrity-and-auto-recovery
- [ ] Provide token status list response (with bitwise AND `&`)
- [ ] Cache response for 30 seconds 

-------------------

### Test cases and code coverage

- [ ] Write unit test to cover added/changed code
- [ ] Update integration tests to cover added/changed code
- [ ] Documentation
